---
title: "MATH 216 Homework 2 Shiny App"
author: "Andrea Narciso"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(babynames)
library(ggplot2movies)
```


## Inputs and Outputs

You can embed Shiny inputs and outputs in your document. Outputs are automatically updated whenever inputs change.  This demonstrates how a standard R plot can be made interactive by wrapping it in the Shiny `renderPlot` function. The `selectInput` and `sliderInput` functions create the input widgets used to drive the plot.

```{r eruptions, echo=FALSE}
inputPanel(
  
  # Input genre (Comedies / Non-Comedies)
  radioButtons("input_genre", label = "Enter Genre:", c("Comedy" = 1, "Non-Comedy" = 0))
  
 )
  

renderPlot({
  
  
  
  # Clean Data
  movies_clean_data <- movies %>% 
    filter(!(is.na(budget)), !(is.na(rating))) 
  movies_clean_data
  
  # Generate Plots
  rating_budget_by_genre <- movies_clean_data %>% 
    select_("budget", "rating", "Comedy") %>% 
    filter(Comedy == input$input_genre)
  rating_budget_by_genre
  
  # Creates Graph
  ggplot(data = rating_budget_by_genre, aes(x=budget, y=rating)) +
    geom_point() + 
    geom_smooth(se=FALSE)
  
  
  
  
})
```
